config/routes.rb
Rails.application.routes.draw do
  resources :cryptos
  root 'cryptos#index'

  # Serve websocket cable requests in-process
  mount ActionCable.server => 'wss://api.bitfinex.com/ws/2'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render html: "ripple my nipples"
  end
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: [:show, :edit, :update, :destroy]

  # GET /cryptos
  # GET /cryptos.json
  def index
    @cryptos = Crypto.all
  end

  # GET /cryptos/1
  # GET /cryptos/1.json
  def show
  end

  # GET /cryptos/new
  def new
    @crypto = Crypto.new
  end

  # GET /cryptos/1/edit
  def edit
  end

  # POST /cryptos
  # POST /cryptos.json
  def create
    @crypto = Crypto.new(crypto_params)

    respond_to do |format|
      if @crypto.save
        format.html { redirect_to @crypto, notice: 'Crypto was successfully created.' }
        format.json { render :show, status: :created, location: @crypto }
      else
        format.html { render :new }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptos/1
  # PATCH/PUT /cryptos/1.json
  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        format.html { redirect_to @crypto, notice: 'Crypto was successfully updated.' }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptos/1
  # DELETE /cryptos/1.json
  def destroy
    @crypto.destroy
    respond_to do |format|
      format.html { redirect_to cryptos_url, notice: 'Crypto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto
      @crypto = Crypto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crypto_params
      params.require(:crypto).permit(:symbol, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/views/cryptos/_form.html.erb
<%= form_with(model: crypto, local: true) do |form| %>
  <% if crypto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crypto.errors.count, "error") %> prohibited this crypto from being saved:</h2>

      <ul>
      <% crypto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol, id: :crypto_symbol %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :crypto_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cryptos/edit.html.erb
<h1>Editing Crypto</h1>

<%= render 'form', crypto: @crypto %>

<%= link_to 'Show', @crypto %> |
<%= link_to 'Back', cryptos_path %>

app/views/cryptos/index.html.erb
<section>
  <div class="tbl-content">
    <table cellpadding="0" cellspacing="0" border="1">
      <thead class = "tbl-header">
        <tr>
          <th>Symbol</th>
          <th>Name</th>
          <th><%= link_to "Coinbase", "https://www.coinbase.com/", :target => "_blank" %></th>
          <th><%= link_to "Bitstamp", "https://www.bitstamp.net/", :target => "_blank" %></th>
          <th><%= link_to "Bitfinex", "https://www.bitfinex.com/", :target => "_blank" %></th>
          <th><%= link_to "Poloniex", "https://poloniex.com/", :target => "_blank" %></th>
          <th><%= link_to "BitTrex", "https://bittrex.com/", :target => "_blank" %></th>
          <th><%= link_to "Kraken", "https://www.kraken.com/", :target => "_blank" %></th>
          <th><%= link_to "HitBTC", "https://hitbtc.com/", :target => "_blank" %></th>
          <th><%= link_to "Exmo", "https://exmo.com/", :target => "_blank" %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class = "column1"><%= image_tag ("bitcoin.png")%></td>
          <td><div class="price_bold">Bitcoin</div><div>(BTC)</div></td> 
          <td id="Coinbase_BTC"><div class="price_bold" id="PRICE_Coinbase_BTC"></div><div id="CHANGE24HOURPCT_Coinbase_BTC"></div></td>
          <td><div class="price_bold" id="PRICE_Bitstamp_BTC"></div><div id="CHANGE24HOURPCT_Bitstamp_BTC"></div></td>
          <td><div class="price_bold" id="PRICE_Bitfinex_BTC"></div><div id="CHANGE24HOURPCT_Bitfinex_BTC"></div></td>
          <td><div class="price_bold" id="PRICE_Poloniex_BTC"></div><div id="CHANGE24HOURPCT_Poloniex_BTC"></div></td>
          <td><div class="price_bold" id="PRICE_BitTrex_BTC"></div><div id="CHANGE24HOURPCT_BitTrex_BTC"></div></td>
          <td><div class="price_bold" id="PRICE_Kraken_BTC"></div><div id="CHANGE24HOURPCT_Kraken_BTC"></div></td>
          <td><div class="price_bold" id="PRICE_HitBTC_BTC"></div><div id="CHANGE24HOURPCT_HitBTC_BTC"></div></td>
          <td><div class="price_bold" id="PRICE_Exmo_BTC"></div><div id="CHANGE24HOURPCT_Exmo_BTC"></div></td>
        </tr>
        <tr>
          <td class = "column1"><%= image_tag ("ethereum.png")%></td>
          <td><div class="price_bold">Ethereum</div><div>(ETH)</div></td>
          <td><div class="price_bold" id="PRICE_Coinbase_ETH"></div><div id="CHANGE24HOURPCT_Coinbase_ETH"></div></td>
          <td><div class="price_bold" id="PRICE_Bitstamp_ETH"></div><div id="CHANGE24HOURPCT_Bitstamp_ETH"></div></td>
          <td><div class="price_bold" id="PRICE_Bitfinex_ETH"></div><div id="CHANGE24HOURPCT_Bitfinex_ETH"></div></td>
          <td><div class="price_bold" id="PRICE_Poloniex_ETH"></div><div id="CHANGE24HOURPCT_Poloniex_ETH"></div></td>
          <td><div class="price_bold" id="PRICE_BitTrex_ETH"></div><div id="CHANGE24HOURPCT_BitTrex_ETH"></div></td>
          <td><div class="price_bold" id="PRICE_Kraken_ETH"></div><div id="CHANGE24HOURPCT_Kraken_ETH"></div></td>
          <td><div class="price_bold" id="PRICE_HitBTC_ETH"></div><div id="CHANGE24HOURPCT_HitBTC_ETH"></div></td>
          <td><div class="price_bold" id="PRICE_Exmo_ETH"></div><div id="CHANGE24HOURPCT_Exmo_ETH"></div></td>
        </tr>
        <tr>
          <td class = "column1"><%= image_tag ("litecoin.png")%></td>
          <td><div class="price_bold">Litecoin</div><div>(LTC)</div></td>
          <td><div class="price_bold" id="PRICE_Coinbase_LTC"></div><div id="CHANGE24HOURPCT_Coinbase_LTC"></div></td>
          <td><div class="price_bold" id="PRICE_Bitstamp_LTC"></div><div id="CHANGE24HOURPCT_Bitstamp_LTC"></div></td>
          <td><div class="price_bold" id="PRICE_Bitfinex_LTC"></div><div id="CHANGE24HOURPCT_Bitfinex_LTC"></div></td>
          <td><div class="price_bold" id="PRICE_Poloniex_LTC"></div><div id="CHANGE24HOURPCT_Poloniex_LTC"></div></td>
          <td><div class="price_bold" id="PRICE_BitTrex_LTC"></div><div id="CHANGE24HOURPCT_BitTrex_LTC"></div></td>
          <td><div class="price_bold" id="PRICE_Kraken_LTC"></div><div id="CHANGE24HOURPCT_Kraken_LTC"></div></td>
          <td><div class="price_bold" id="PRICE_HitBTC_LTC"></div><div id="CHANGE24HOURPCT_HitBTC_LTC"></div></td>
          <td><div class="price_bold" id="PRICE_Exmo_LTC"></div><div id="CHANGE24HOURPCT_Exmo_LTC"></div></td>
        </tr>
        <tr>
          <td class = "column1"><%= image_tag ("bitcoincash.png")%></td>
          <td><div class="price_bold">Bitcoin Cash</div><div>(BCH)</div></td> 
          <td><div class="price_bold" id="PRICE_Coinbase_BCH"></div><div id="CHANGE24HOURPCT_Coinbase_BCH"></div></td>
          <td><div class="price_bold" id="PRICE_Bitstamp_BCH"></div><div id="CHANGE24HOURPCT_Bitstamp_BCH"></div></td>
          <td><div class="price_bold" id="PRICE_Bitfinex_BCH"></div><div id="CHANGE24HOURPCT_Bitfinex_BCH"></div></td>
          <td><div class="price_bold" id="PRICE_Poloniex_BCH"></div><div id="CHANGE24HOURPCT_Poloniex_BCH"></div></td>
          <td><div class="price_bold" id="PRICE_BitTrex_BCH"></div><div id="CHANGE24HOURPCT_BitTrex_BCH"></div></td>
          <td><div class="price_bold" id="PRICE_Kraken_BCH"></div><div id="CHANGE24HOURPCT_Kraken_BCH"></div></td>
          <td><div class="price_bold" id="PRICE_HitBTC_BCH"></div><div id="CHANGE24HOURPCT_HitBTC_BCH"></div></td>
          <td><div class="price_bold" id="PRICE_Exmo_BCH"></div><div id="CHANGE24HOURPCT_Exmo_BCH"></div></td>
        </tr>
        <tr>
          <td class = "column1"><%= image_tag ("ripple.png")%></td>
          <td><div class="price_bold">Ripple</div><div>(XRP)</div></td> 
          <td><div class="price_bold" id="PRICE_Coinbase_XRP"></div><div id="CHANGE24HOURPCT_Coinbase_XRP"></div></td>
          <td><div class="price_bold" id="PRICE_Bitstamp_XRP"></div><div id="CHANGE24HOURPCT_Bitstamp_XRP"></div></td>
          <td><div class="price_bold" id="PRICE_Bitfinex_XRP"></div><div id="CHANGE24HOURPCT_Bitfinex_XRP"></div></td>
          <td><div class="price_bold" id="PRICE_Poloniex_XRP"></div><div id="CHANGE24HOURPCT_Poloniex_XRP"></div></td>
          <td><div class="price_bold" id="PRICE_BitTrex_XRP"></div><div id="CHANGE24HOURPCT_BitTrex_XRP"></div></td>
          <td><div class="price_bold" id="PRICE_Kraken_XRP"></div><div id="CHANGE24HOURPCT_Kraken_XRP"></div></td>
          <td><div class="price_bold" id="PRICE_HitBTC_XRP"></div><div id="CHANGE24HOURPCT_HitBTC_XRP"></div></td>
          <td><div class="price_bold" id="PRICE_Exmo_XRP"></div><div id="CHANGE24HOURPCT_Exmo_XRP"></div></td>
        </tr>
        <tr>
          <td class = "column1"><%= image_tag ("monero.png")%></td>
          <td><div class="price_bold">Monero</div><div>(XMR)</div></td>
          <td><div class="price_bold" id="PRICE_Coinbase_XMR"></div><div id="CHANGE24HOURPCT_Coinbase_XMR"></div></td>
          <td><div class="price_bold" id="PRICE_Bitstamp_XMR"></div><div id="CHANGE24HOURPCT_Bitstamp_XMR"></div></td>
          <td><div class="price_bold" id="PRICE_Bitfinex_XMR"></div><div id="CHANGE24HOURPCT_Bitfinex_XMR"></div></td>
          <td><div class="price_bold" id="PRICE_Poloniex_XMR"></div><div id="CHANGE24HOURPCT_Poloniex_XMR"></div></td>
          <td><div class="price_bold" id="PRICE_BitTrex_XMR"></div><div id="CHANGE24HOURPCT_BitTrex_XMR"></div></td>
          <td><div class="price_bold" id="PRICE_Kraken_XMR"></div><div id="CHANGE24HOURPCT_Kraken_XMR"></div></td>
          <td><div class="price_bold" id="PRICE_HitBTC_XMR"></div><div id="CHANGE24HOURPCT_HitBTC_XMR"></div></td>
          <td><div class="price_bold" id="PRICE_Exmo_XMR"></div><div id="CHANGE24HOURPCT_Exmo_XMR"></div></td>
        </tr>
        <tr>
          <td class = "column1"><%= image_tag ("dash.png")%></td>
          <td><div class="price_bold">Dash</div><div>(DASH)</div></td>
          <td><div class="price_bold" id="PRICE_Coinbase_DASH"></div><div id="CHANGE24HOURPCT_Coinbase_DASH"></div></td>
          <td><div class="price_bold" id="PRICE_Bitstamp_DASH"></div><div id="CHANGE24HOURPCT_Bitstamp_DASH"></div></td>
          <td><div class="price_bold" id="PRICE_Bitfinex_DASH"></div><div id="CHANGE24HOURPCT_Bitfinex_DASH"></div></td>
          <td><div class="price_bold" id="PRICE_Poloniex_DASH"></div><div id="CHANGE24HOURPCT_Poloniex_DASH"></div></td>
          <td><div class="price_bold" id="PRICE_BitTrex_DASH"></div><div id="CHANGE24HOURPCT_BitTrex_DASH"></div></td>
          <td><div class="price_bold" id="PRICE_Kraken_DASH"></div><div id="CHANGE24HOURPCT_Kraken_DASH"></div></td>
          <td><div class="price_bold" id="PRICE_HitBTC_DASH"></div><div id="CHANGE24HOURPCT_HitBTC_DASH"></div></td>
          <td><div class="price_bold" id="PRICE_Exmo_DASH"></div><div id="CHANGE24HOURPCT_Exmo_DASH"></div></td>
        </tr>
        <tr>
          <td class = "column1"><%= image_tag ("etherclassic.png")%></td>
          <td><div class="price_bold">Ethereum Classic</div><div>(ETC)</div></td>
          <td><div class="price_bold" id="PRICE_Coinbase_ETC"></div><div id="CHANGE24HOURPCT_Coinbase_ETC"></div></td>
          <td><div class="price_bold" id="PRICE_Bitstamp_ETC"></div><div id="CHANGE24HOURPCT_Bitstamp_ETC"></div></td>
          <td><div class="price_bold" id="PRICE_Bitfinex_ETC"></div><div id="CHANGE24HOURPCT_Bitfinex_ETC"></div></td>
          <td><div class="price_bold" id="PRICE_Poloniex_ETC"></div><div id="CHANGE24HOURPCT_Poloniex_ETC"></div></td>
          <td><div class="price_bold" id="PRICE_BitTrex_ETC"></div><div id="CHANGE24HOURPCT_BitTrex_ETC"></div></td>
          <td><div class="price_bold" id="PRICE_Kraken_ETC"></div><div id="CHANGE24HOURPCT_Kraken_ETC"></div></td>
          <td><div class="price_bold" id="PRICE_HitBTC_ETC"></div><div id="CHANGE24HOURPCT_HitBTC_ETC"></div></td>
          <td><div class="price_bold" id="PRICE_Exmo_ETC"></div><div id="CHANGE24HOURPCT_Exmo_ETC"></div></td>
        </tr>
      </tbody>
    </table>
  </div>
</section>

app/views/cryptos/new.html.erb
<h1>New Crypto</h1>

<%= render 'form', crypto: @crypto %>

<%= link_to 'Back', cryptos_path %>

app/views/cryptos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Symbol:</strong>
  <%= @crypto.symbol %>
</p>

<p>
  <strong>Price:</strong>
  <%= @crypto.price %>
</p>

<%= link_to 'Edit', edit_crypto_path(@crypto) %> |
<%= link_to 'Back', cryptos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cgd</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.7.2/socket.io.js"></script>
    <%= yield %>
  </body>
</html>